apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: hello-world
spec:
    replicas: 1
    template: 
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: hello-world
              image: hello-world:v1
